version: '3'
services:
  podcast_gui:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "9110:3000"
    restart: unless-stopped
    environment:
      - http_proxy=http://10.60.28.99:81
      - https_proxy=http://10.60.28.99:81
      - HTTP_PROXY=http://10.60.28.99:81
      - HTTPS_PROXY=http://10.60.28.99:81
    networks:
      - podcast_network
networks:
  podcast_network:
    driver: bridge